# Generated by Django 5.0.6 on 2024-06-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_Customer_Data',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=10, unique=True)),
                ('customer_email', models.EmailField(max_length=100, unique=True)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_state', models.CharField(max_length=100)),
                ('customer_country', models.CharField(max_length=100)),
                ('customer_pin', models.CharField(max_length=6)),
                ('customer_services', models.CharField(max_length=50)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_message', models.TextField()),
                ('rating', models.IntegerField(max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_Customers.gym_customer_data')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_subject', models.CharField(max_length=100)),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_Customers.gym_customer_data')),
            ],
        ),
    ]
