# Generated by Django 5.0.6 on 2024-06-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gym_Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_Staff_Data',
            fields=[
                ('staff_user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('staff_user_name', models.CharField(max_length=100)),
                ('staff_user_mobile', models.CharField(max_length=10)),
                ('staff_user_email', models.EmailField(max_length=100)),
                ('staff_user_password', models.CharField(max_length=20)),
                ('staff_user_address', models.CharField(max_length=100)),
                ('staff_user_city', models.CharField(max_length=100)),
                ('staff_user_state', models.CharField(max_length=100)),
                ('staff_user_country', models.CharField(max_length=100)),
                ('staff_user_pin', models.CharField(max_length=6)),
                ('staff_user_designation', models.CharField(max_length=20)),
                ('staff_user_image', models.ImageField(blank=True, null=True, upload_to='gym_staff_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='Gallery_Images/')),
                ('about_image', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Gym_Staff.gym_staff_data')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_text', models.TextField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='Blog_Images/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to='Gym_Staff.gym_staff_data')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gym_Customers.query')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_subject', models.CharField(max_length=255)),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_queries', to='Gym_Staff.gym_staff_data')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_queries', to='Gym_Staff.gym_staff_data')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Query_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gym_Staff.staff_query')),
            ],
        ),
    ]
